import os
import json
import time
import requests
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

class DummyLLMClient:
    def generate_json(self, system_prompt: str, user_prompt: str, model: str = None) -> dict:
        return {"mock": "data", "status": "success"}

    def generate_text(self, system_prompt: str, user_prompt: str) -> str:
        return "Mock response generated by DummyLLMClient."

class FreeLLMClient:
    def __init__(self):
        self.groq_api_key = os.environ.get("GROQ_API_KEY")
        self.gemini_api_key = os.environ.get("GEMINI_API_KEY")
        self.ollama_base_url = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434/v1")
        
        if self.groq_api_key:
            self.provider = "groq"
            self.base_url = "https://api.groq.com/openai/v1"
            self.api_key = self.groq_api_key
            self.default_model = "mixtral-8x7b-32768"
        elif self.gemini_api_key:
            self.provider = "gemini"
            self.base_url = "https://generativelanguage.googleapis.com/v1beta/openai" # Simulated endpoint or use proper URL
            self.api_key = self.gemini_api_key
            self.default_model = "gemini-1.5-flash"
        else:
            self.provider = "ollama"
            self.base_url = self.ollama_base_url
            self.api_key = "dummy"
            self.default_model = "llama3"

    def _call_api_with_retry(self, payload: dict, is_json: bool = False, max_retries: int = 3):
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        for attempt in range(max_retries):
            try:
                response = requests.post(f"{self.base_url}/chat/completions", headers=headers, json=payload, timeout=30)
                if response.status_code == 200:
                    resp_data = response.json()
                    content = resp_data["choices"][0]["message"]["content"]
                    if is_json:
                        return json.loads(content)
                    return content
                elif response.status_code == 429:
                    time.sleep(2 ** attempt)
                    continue
                else:
                    print(f"API Error: {response.status_code} - {response.text}")
                    break
            except Exception as e:
                print(f"Request Error: {e}")
                time.sleep(2 ** attempt)
        
        # Fallback to dummy client if all retries fail or an error occurs
        print("Falling back to DummyLLMClient")
        dummy = DummyLLMClient()
        return dummy.generate_json("", "") if is_json else dummy.generate_text("", "")

    def generate_json(self, system_prompt: str, user_prompt: str, model: str = None) -> dict:
        payload = {
            "model": model or self.default_model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.0,
            "response_format": {"type": "json_object"}
        }
        return self._call_api_with_retry(payload, is_json=True)

    def generate_text(self, system_prompt: str, user_prompt: str) -> str:
        payload = {
            "model": self.default_model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.0
        }
        return self._call_api_with_retry(payload, is_json=False)

if __name__ == "__main__":
    client = FreeLLMClient()
    print(f"Active Provider: {client.provider}")
    print(f"Base URL: {client.base_url}")
    # text = client.generate_text("You are a helpful assistant", "Hello")
    # print(text)
